CREATE DATABASE IF NOT EXISTS devbooks;
USE devbooks;

DROP TABLE IF EXISTS users;
CREATE TABLE users (
  id INTEGER NOT NULL AUTO_INCREMENT,
  name VARCHAR(200) NOT NULL,
  user_name VARCHAR(200) NOT NULL UNIQUE ,
  email VARCHAR(200) NOT NULL UNIQUE ,
  password VARCHAR(20) NOT NULL UNIQUE ,
  create_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (id)
)ENGINE = INNODB;